version: '3.8'

services:
  # --- PROJECT 1: NODEJS + MYSQL (Cũ) ---
  backend-node:
    build: .
    container_name: project1_node
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db-mysql
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7
    container_name: project1_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: studb

  # --- PROJECT 2: PHP (Mới thêm) ---
  web-php:
    build: ./project2_php   # Dùng Dockerfile trong thư mục mới
    container_name: project2_php
    ports:
      - "8081:80"           # Chạy ở cổng 8081